### ISSUE TITLE
Format `date`according to `lang`

### ISSUE THREAD

**Issue by salim-b** [Wandmalfarbe/pandoc-latex-template#105]
Would it be possible to have the `date`, which by default is used on the title page and in the `header-right`, formatted according to the `lang` code specified? E.g. if I set `lang: de-DE` and `date: 2019-07-22` in the YAML block, the correctly formatted date in the PDF should read `22.07.2019`.

Besides another option like `long-date: true/false` would be nice. If `true`, the above example should result in `22. Juli 2019` in case of `lang: de-DE` and `July 22, 2019` (or `22 July 2019`) in case of `lang: en-US` for example.

**Comment by Wandmalfarbe** [comment]
This specific behaviour is not possible because I just pass the pandoc variable `$date$` to the LaTeX file (no parsing or manipulation can be done with the pandoc templating language). However you can always specify another date format that gets passed to the template:

```markdown
---
title: "Example for a Formatted Date on the Titlepage"
author: [Author]
date: "22. Juli 2019"
subject: "Markdown"
keywords: [Markdown, Example]
lang: "de"
...

# Vinaque sanguine metuenti cuiquam Alcyone fixus

## Aesculeae domus vincemur et Veneris adsuetus lapsum

Lorem markdownum Letoia, et alios: figurae flectentem annis aliquid Peneosque ab
esse, obstat gravitate. Obscura atque coniuge, per de coniunx, sibi **medias
commentaque virgine** anima tamen comitemque petis, sed. In Amphion vestros
hamos ire arceor mandere spicula, in licet aliquando.
```

![basic-example-date](https://user-images.githubusercontent.com/17237627/62425264-7777a900-b6d9-11e9-8a43-c1944857a5b4.png)

**Comment by salim-b** [comment]
Ok, I see. Thanks for the explanation!
