### ISSUE TITLE
Support for NOTE, WARNING and INFO boxes...

### ISSUE THREAD

**Issue by wxguy** [Wandmalfarbe/pandoc-latex-template#115]
I do not know if it really can be implemented using a pandoc template. But if there is any way ahead, I would like to see the support for NOTE, WARNING and INFO boxes with corresponding icons within the box. This would be fantastic as there is no solution exist in markdown at the moment.

**Comment by cagix** [comment]
it should be easy to define this environments in a latex snippet and include this via -H option ...

On 2. Sep 2019, at 07:33, wxguy <notifications@github.com<mailto:notifications@github.com>> wrote:


I do not know if it really can be implemented using a pandoc template. But if there is any way ahead, I would like to see the support for NOTE, WARNING and INFO boxes with corresponding icons within the box. This would be fantastic as there is no solution exist in markdown at the moment.

**Comment by cagix** [comment]
and for markdown support, special divs (like ':::note ... :::' could be used, which could be translated to the included definitions via a short lua filter ...


On 2. Sep 2019, at 11:52, Carsten Gips <notifications@github.com<mailto:notifications@github.com>> wrote:

it should be easy to define this environments in a latex snippet and include this via -H option ...

On 2. Sep 2019, at 07:33, wxguy <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I do not know if it really can be implemented using a pandoc template. But if there is any way ahead, I would like to see the support for NOTE, WARNING and INFO boxes with corresponding icons within the box. This would be fantastic as there is no solution exist in markdown at the moment.

**Comment by wxguy** [comment]
`it should be easy to define this environments in a latex snippet and include this via -H option ...`
&&
`and for markdown support, special divs (like ':::note ... :::' could be used, which could be translated to the included definitions via a short lua filter ...`

This is the first time I am getting some positive response for the same query. May I go further to ask you to provide some example please.

**Comment by Wandmalfarbe** [comment]
> special divs (like `:::note ... :::` could be used, which could be translated to the included definitions via a short lua filter

Yes thats the only solution when you want to write entirely in markdown. I think I saw a GitHub repo that did exactly this. Will have to do some digging ... It might take some time because I'm a bit busy at the moment.

**Comment by daamien** [comment]
Hello,

For the last 5 years, we've been writing training manuals in markdown and we are using `<div>` tags to make a difference between the slides content and the teachers notes (handout)

For instance:

~~~markdown

## Title of the slide

<div class="slide-content">
This will appear on the revealjs slideshow
</div>

<div class="notes">
This will appear on the revealjs slideshow AND the PDF handout
</div>

~~~

The `<div class="notes">` is similar to `:::notes` pandoc will automatically remove it from the slideshow export

In the PDF handout we make an empahsis on the slides ( the `<div class="slide-content">` tags ) with the [pandoc-latex-admonition] filter and this yaml config in the document header

~~~yaml
pandoc-latex-admonition:
  - color: LightPink
    classes: [important]
    linewidth: 4
  - color: Khaki
    classes: [warning]
    linewidth: 4
  - color: DarkSeaGreen
    classes: [tip]
    linewidth: 4
  - color: Ivory
    classes: [note]
    linewidth: 4
  - color: DodgerBlue
    classes: [slide-content]
    linewidth: 4
~~~

[pandoc-latex-admonition]: https://github.com/chdemko/pandoc-latex-admonition

As you can see we have defined several classes that we can use in diferent context :

~~~markdown

<div class="warning">
This is an **ALERT** !!!!!
</div>

<div class="tip">
This is a just a _simple_  advice.
</div>

~~~

Here's an example:

* Mardown source: https://github.com/dalibo/workshops/blob/master/fr/110-postgresql_11.md
* PDF handout: https://public.dalibo.com/exports/formation/workshops/fr/110-postgresql_11.pdf
* Reveal Slides: https://public.dalibo.com/exports/formation/workshops/fr/110-postgresql_11.slides.html#/


At one point we also used the [pandoc-latex-environment] filter but it was a bit harder to set up so we  switched to [pandoc-latex-admonition]  last year.

[pandoc-latex-environment]: https://github.com/chdemko/pandoc-latex-environment


Hope this helps :-)

**Comment by wxguy** [comment]
@daamien ,

Even though I did not get the desired result (some icon like bulb for info), it solved my problem partially. 

I keep the issue open if the author feels that support for my request is possible and likely to be implemented. Otherwise, you can close it, if you wish.

**Comment by daamien** [comment]
@wxguy : Take a look at the [pandoc-latex-tip] filter. To my knowledge, this is the closest thing to what you want... I guess you could even try to make use [pandoc-latex-tip] and [pandoc-latex-environment] at the same time in order to have a box and an icon...

* markdown source: https://raw.githubusercontent.com/chdemko/pandoc-latex-tip/master/docs/images/pandoc-latex-tip-sample.txt
* PDF output : https://github.com/chdemko/pandoc-latex-tip/blob/develop/docs/images/pandoc-latex-tip-sample.pdf

We don't use this filter in our production toolchain because it requires the `Pillow` python library which is a real pain to install and maintain. 

 [pandoc-latex-tip]: https://github.com/chdemko/pandoc-latex-tip
 [pandoc-latex-environment]: https://github.com/chdemko/pandoc-latex-environment

That being said, I think eisvogel template should work without any mandatory filter and without any python dependency.

**Comment by cagix** [comment]
you could do something like

1. define your latex environment `fluppie` in `wuppie. tex` using `\newenvironment` ...
2. use a div in your markdown `wuppie. md`:
    ```
    ::: fluppie
    .... your content in your environment...
    :::
    ```
3. define a lua filter, which would replace the `fluppie` div with your latex environment, i.e. the function needs to be registered for divs and would emit a raw-latex for `\begin{fluppie}`, the content of the div and a raw-latex for `\end{fluppie}`.
4. call `pandoc --lua-filter=wuppie. lua -H wuppie. tex wuppie.md -o wuppie. pdf`

see pandoc manual for divs und lua-filter, also there is a pandoc/lua-filter repo here on github containing plenty sample filter.

in my [pandoc-lecture](https://github.com/cagix/pandoc-lecture) i use this technique for e.g. `blueArrow` (ok, its a span and not a div, but the mechanism is the same).

while debugging its been helpful to me to have pandoc generate latex output instead of pdf ...

On 2. Sep 2019, at 14:04, wxguy <notifications@github.com<mailto:notifications@github.com>> wrote:


it should be easy to define this environments in a latex snippet and include this via -H option ...
&&
and for markdown support, special divs (like ':::note ... :::' could be used, which could be translated to the included definitions via a short lua filter ...

This is the first time I am getting some positive response for the same query. May I go further to ask you to provide some example please.

**Comment by wxguy** [comment]
I have found one more technique to use what I wanted using the beautiful `awesomebox` package. Firstly, I have included the line `\usepackage{awesomebox}` immediately after the `blockquote` section in `eisvogel.tex` template file. Then used the command `\notebox{Some useful long information }` and `\warningbox{some important warning message}` and so on in the markdown file. No header or any other tweaking is required. The resulting admonition blocks are really awesome. 
The result can be seen in this official pdf file http://mirrors.ctan.org/graphics/awesomebox/awesomebox.pdf. 

The only catch is that the syntax to put different boxes are different from standard markdown. But that is OK for me considering the beautiful results I get. Hope this message helps someone in future.

**Comment by cagix** [comment]
> The only catch is that the syntax to put different boxes are different from standard markdown. 

also, using raw latex macros any markdown inside `\notebox{Some **useful** _long_ information}` will not be interpreted by pandoc ...

**Comment by cagix** [comment]
> Firstly, I have included the line \usepackage{awesomebox} immediately after the blockquote section in eisvogel.tex template file.

you could put this line in a separate tex-file and include this via -H ... this way there is no need to modify the eisvogel template, which makes any updates easier :)

**Comment by Wandmalfarbe** [comment]
I've added the example `boxes-with-pandoc-latex-environment-and-awesomebox` that demonstrates how a custom environment and a filter can be used to render admonition boxes.

**Comment by wxguy** [comment]
Wow. Great. Thanks.

**Comment by yuuuxt** [comment]
I notice that there is always an extra blank line at the end for each box (longer vertical color bar), is this intended and can I modify this? thx

**Comment by Wandmalfarbe** [comment]
> I notice that there is always an extra blank line at the end for each box (longer vertical color bar), is this intended and can I modify this? thx

That is a bug in the `pandoc-latex-environment` filter. A fix is already proposed (https://github.com/chdemko/pandoc-latex-environment/pull/7) but the PR is not merged yet.

**Comment by yuuuxt** [comment]
> 
> 
> > I notice that there is always an extra blank line at the end for each box (longer vertical color bar), is this intended and can I modify this? thx
> 
> That is a bug in the `pandoc-latex-environment` filter. A fix is already proposed ([chdemko/pandoc-latex-environment#7](https://github.com/chdemko/pandoc-latex-environment/pull/7)) but the PR is not merged yet.

I manually modified and installed the package. thanks for helping!
