### ISSUE TITLE
page breaks on top level heading (h1 / #)

### ISSUE THREAD

**Issue by eben-roux** [Wandmalfarbe/pandoc-latex-template#14]
I really like this template.

I'm using it for a book I'm self-publishing.  As I understand you are not specifically targeting books but since my book show sample C# code I need something to properly format the code and your template does the trick.

Using `documentclass: book` seems to break things so I've removed that.

I would like to place page breaks on the top level headings (# in my markdown).  For that I've tried the `titlesec` package and include a `header-includes` to a `titlesec.tex` file with the following:

```
% titlesec setup
\usepackage{titlesec}
\newcommand{\sectionbreak}{\clearpage}
```

However, this results in the following error:

```
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.100 t
```

This is really my first outing with pandoc so any help would be appreciated.  I have been struggling quite a while trying to get a decent output and I feel that I'm almost there :)

**Comment by martinlarsson** [comment]
I too struggled with this a while back and couldnt get it to work. Ended up with entering `\newpage` at the top of each markdown file (ie top level heading).

**Comment by Wandmalfarbe** [comment]
I'm glad you like it! This really means a lot to me.

First of all I used the KOMA-Script class `scrartcl` as the document class because it has [some advantages](https://tex.stackexchange.com/a/1360) over the default `article` class. For typesetting a book I recommend the corresponding KOMA-Script class `scrbook` instead of the default `book`. All the examples should work with the KOMA-Script class.

To get the correct chapter headings (and page breaks before them) you need to tell pandoc that it should convert first level headings `#` to chapters with the command `--top-level-division=chapter` ([-> Manual](https://pandoc.org/MANUAL.html#options-affecting-specific-writers)).

There will be one blank page before each chapter because the template is two-sided per default (I think I should change that). So if you plan to publish your book as a PDF and don't need a blank page you should add the class option `onesided` which can be done by supplying a template variable `-V classoption=oneside` ([-> Manual](https://pandoc.org/MANUAL.html#variables-for-latex)).

Unfortunately I never really tested chapters with my template so there are some strange chapter headings. I filed a new Issue (https://github.com/Wandmalfarbe/pandoc-latex-template/issues/16) and try to figure out what's wrong.

**Comment by eben-roux** [comment]
Thanks a stack for the feedback.  I'll give it a go.

**Comment by eben-roux** [comment]
@martinlarsson: my brain only really registered your message now :)

My entire document is in one markdown file.  Would one add that `\newline` before each `# Heading` then?

**Comment by martinlarsson** [comment]
Yeah, I think that would do the trick. But `\newpage` instead of `\newline` :)

**Comment by eben-roux** [comment]
*lol*: goodness... thanks!

**Comment by Wandmalfarbe** [comment]
Just a quick note for everyone having the same problem. You can insert two commands into the template with `header-includes` to create a pagebreak for every top level heading (see also #81):

```markdown
---
title: "Example PDF"
author: [Author]
date: "2017-02-20"
subject: "Markdown"
keywords: [Markdown, Example]
lang: "en"
header-includes: |
    \usepackage{sectsty}
    \sectionfont{\clearpage}
...

# Vinaque sanguine metuenti cuiquam Alcyone fixus

Lorem markdownum Letoia, et alios: figurae flectentem annis aliquid Peneosque ab
esse, obstat gravitate. Obscura atque coniuge, per de coniunx, sibi **medias
commentaque virgine** anima tamen comitemque petis, sed. In Amphion vestros
hamos ire arceor mandere spicula, in licet aliquando.

# Aesculeae domus vincemur et Veneris adsuetus lapsum

Lorem markdownum Letoia, et alios: figurae flectentem annis aliquid Peneosque ab
esse, obstat gravitate. Obscura atque coniuge, per de coniunx, sibi **medias
commentaque virgine** anima tamen comitemque petis, sed. In Amphion vestros
hamos ire arceor mandere spicula, in licet aliquando.
```
