### ISSUE TITLE
Russian text in inline block with --listing

### ISSUE THREAD

**Issue by Orygeunik** [Wandmalfarbe/pandoc-latex-template#153]
Create md-doc and placed in any space follow text:
Text `Русский текст` other text

Try to run converting md to pdf (on windows system)...

Command to starting converting:
`pandoc "t.md" -o t.pdf -t latex --pdf-engine=xelatex -f markdown --template ".\settings\eisvogel.tex" --listing`

And result:
`
Error producing PDF.
! Undefined control sequence.
\lst@arg ->╨а
            ╤Г╤Б╤Б╨║╨╕╨╣ ╤В╨╡╨║╤Б╤В
l.386 Text \passthrough{\lstinline!╨а╤Г╤Б╤Б╨║╨╕╨╣ ╤В╨╡╨║╤Б╤В!}
`

If disable option '--listing', then pdf build successful

**Comment by Wandmalfarbe** [comment]
To quote the `listingsutf8` documentation:

> Package [listings](https://ctan.org/pkg/listings) does not support files with multi-byte encodings such as UTF-8.

This means that typesetting Russian text in `listings` is not possible without extensive work. It may be possible to redefine all the `listings` commands to use `listingsutf8` instead but I don't have the time to experiment with this (PRs are welcome though).

As you already noticed, a possible workaround is running pandoc without `--listings` so that it typesets code using the `verbatim` environment.
