### ISSUE TITLE
Load awesomebox when pandoc-latex-environment is declared in frontmatter

### ISSUE THREAD

**Issue by daamien** [Wandmalfarbe/pandoc-latex-template#154]
Hi !

It seems the fontawesome package is required when using the pandoc-latex-environment filter

As described in this example:
https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/examples/boxes-with-pandoc-latex-environment-and-awesomebox/boxes.md

I wonder if we could avoid the annoying `header-includes:` parameter by detecting if pandoc-latex-environment is defined and load the package only when required

```latex
$if(pandoc-latex-environment)$
\usepackage{awesomebox}
$endif$
```
If you think it's ok, I can send a PR for that

**Comment by daamien** [comment]
It appears that the `awesomebox` depends on the `fontawesome5` package which is incompatible with some latex distributions. 

For older distributions, you have to load `awesombox-compat` instead

https://github.com/milouse/latex-awesomebox#compatibility

User may have to specify a different package depending on their environement, so it's better to leave this outside of the template. 

I'm closing this issue. Sorry for the noise...

**Comment by Wandmalfarbe** [comment]
> It seems the fontawesome package is required when using the pandoc-latex-environment filter

That's just the setup for the specific example. The filter `pandoc-latex-environment` doesn't need packages. I use the filter to generate `awesomebox` environments which need the `fontawesome` package.

> I wonder if we could avoid the annoying `header-includes:` parameter by detecting if pandoc-latex-environment is defined and load the package only when required
> 
> ```
> $if(pandoc-latex-environment)$
> \usepackage{awesomebox}
> $endif$
> ```

That would be possible but the package might get loaded when it is not needed because one can use the filter `pandoc-latex-environment` to generate other environments (for example a [`tcolorbox`](https://tex.stackexchange.com/questions/36524/how-to-put-a-framed-box-around-text-math-environment/36528)).

I prefer to keep the template clean from such changes because there are a handful of filters that might need additional packages (and I can't account for all possible combinations).
