### ISSUE TITLE
show image full size, crop if needed

### ISSUE THREAD

**Issue by basbebe** [Wandmalfarbe/pandoc-latex-template#180]
I have an image pdf that is exactly as wide as the page I plan to output (output is A4, image is A5 wide).

this scales the image down (to fit inside page borders?):
```
![](./image.pdf){ width=100% }
```

this places the image too far right:
```
![](./image.pdf){ width=21cm }
```

I would like the image to be centered, full size and cropped if necessary.
Is this possible?
A background image for only a single page would also work for me but I guess this is not an option?

Thanks!

**Comment by Wandmalfarbe** [comment]
> this scales the image down (to fit inside page borders?):
> 
> ```
> ![](./image.pdf){ width=100% }
> ```

Yes, that's [exactly the case](https://pandoc.org/MANUAL.html#extension-link_attributes). The image will never exceed the content area in height nor in width. This is the produces LaTeX code:

``` latex
\includegraphics[width=1\textwidth,height=\textheight]{./image.pdf}
```

> this places the image too far right:
> 
> ```
> ![](./image.pdf){ width=21cm }
> ```

The image is a bit too high for the page so it gets scaled a little. Even defining a manual width doesn't solve this as one can see from the produced LaTeX:

``` latex
\includegraphics[width=30cm,height=\textheight]{./image.pdf}
```

> I would like the image to be centered, full size and cropped if necessary.
> Is this possible?

One option is to reduce the height of the image so it fits the page vertically. It would then be scaled to fill the content area horizontally.

Images smaller than the page are currently left aligned. I can implement a method to center align them but that is currently not very high on my to-do list. There is an [open issue for that feature request](https://github.com/Wandmalfarbe/pandoc-latex-template/issues/173).

> A background image for only a single page would also work for me but I guess this is not an option?

That seems like a hack to solve the issue because you would need to reserve some space on the page for the image to be visible and recompile everything once text wraps onto a new page...
