### ISSUE TITLE
rename eisvogel.tex to eisvogel.latex

### ISSUE THREAD

**Issue by HanEmile** [Wandmalfarbe/pandoc-latex-template#182]
This step in the "Installation" section of the readme irritated me:

>  Move the template `eisvogel.tex` to your pandoc templates folder and rename the file to `eisvogel.latex`

Wouldn't it be useful to eliminate that renaming step, by renaming the file directly in the release?

Am I missing something here (backwards compatibility or so) making this infeasable?

**Comment by cagix** [comment]
my thoughts exactly :)

**Comment by pykong** [comment]
Exactly. This is extremely confusing.

**Comment by Fabioni** [comment]
Then let's change it or what's stopping us?

**Comment by HanEmile** [comment]
Well, I first thought of directly submitting a PR, but this seemed so simple that I thought this might have some deeper meaning that isn't visible on first sight. As nobody has had any problem with this in the last half year and the overall mood for renaming this is fairly positive, there shouldn't be a problem with renaming it.

**Comment by Wandmalfarbe** [comment]
The renaming in the released artifacts seems like a reasonable step. I hesitated because the file in the repository was intentionally named *eisvogel.tex* to get syntax highlighting and filetype recognition. If the file has a different name when released it's going to confuse people who install directly from the repository master branch.

However, one should only install a stable release from the releases page, so this is not a major issue.
