### ISSUE TITLE
Add cover support

### ISSUE THREAD

**Issue by Voleking** [Wandmalfarbe/pandoc-latex-template#3]
If I use this template to generate a long articles or notes. A cover and back cover support will be nice!

**Comment by Wandmalfarbe** [comment]
I will look into cover support.

**Comment by Wandmalfarbe** [comment]
There is now support for a LaTeX title page. You can use the following YAML front matter in your markdown file:

```markdown
---
title: "Vinaque sanguine metuenti cuiquam Alcyone fixus"
author: [Author Name]
date: 2017-02-20
subtitle: "Aesculeae domus vincemur et Veneris adsuetus lapsum"
titlepage: true
titlepage-color: 06386e
titlepage-text-color: ffffff
titlepage-rule-color: ffffff
titlepage-rule-height: 1
...
```

All these variables are used when building the title page. You can also use the default styling by just specifying `titlepage: true`:

```markdown
---
title: "Vinaque sanguine metuenti cuiquam Alcyone fixus"
author: [Author Name]
date: 2017-02-20
subtitle: "Aesculeae domus vincemur et Veneris adsuetus lapsum"
titlepage: true
...
```

I might add some documentation of these variables in the future.

The back cover easily can be implemented the same way I implemented the title page. You can look at the LaTeX file between the comments `% begin titlepage` and `% end titlepage`. I don't consider the back cover to be part of this template because it is not intended for books.

**Comment by Voleking** [comment]
@Wandmalfarbe I really appreciate your nice job. I know little about latex, but now I can make some changes for my own use on the basis of your template.

**Comment by e1th0r** [comment]
I've working with this template

`https://github.com/Wandmalfarbe/pandoc-latex-template`

And results seems to be good 

[example.pdf](https://github.com/Wandmalfarbe/pandoc-latex-template/files/2617248/example.pdf)

**Comment by e1th0r** [comment]
Comment for to generate pdf is like

pandoc guides/titlepage.md  guides/Team-Start-Example.md -o example.pdf --template eisvogel.latex

I will be fixing some details
