### ISSUE TITLE
What is the recommended way to change mainfont, sansfont, and monofont?

### ISSUE THREAD

**Issue by georgerbr** [Wandmalfarbe/pandoc-latex-template#59]
Through the CLI? Directly on the source file?

Thanks for any help.

**Comment by Wandmalfarbe** [comment]
That depends on your use case. Here are two scenarios:

1. You want to share the markdown document. You can then add the options directly in the source file to get the same output on different computers without having to remember all the options for the CLI. Multiple files will have the same duplicated options for the `mainfont`, `sansfont` etc..

    Here is an example of a YAML frontmatter with some options:
    ```markdown
    ---
    title: "The Document Title"
    author: [Example Author, Another Author]
    date: "2017-02-20"
    mainfont: "EB Garamond"
    monofont: "Bitstream Vera Mono"
    keywords: [Markdown, Example]
    ...

    The actual document text ...
    ```
2. You changed all the fonts and it is unlikely that you change them ever again. You can invoke pandoc via makefile or terminal and copy the long CLI-String with all the options. There is no need to specify the options in the source file because the makefile/bash script takes care of it all and defines all the options in a single location.
    
    ```bash
    pandoc example.md -o example.pdf --template eisvogel -V "mainfont=EB Geramond" -V "monofont=Bitstream Vera Mono"
    ```
