### ISSUE TITLE
Curly quotes present in code listings under XeLaTeX engine

### ISSUE THREAD

**Issue by pond** [Wandmalfarbe/pandoc-latex-template#79]
Addressed by:

https://github.com/Wandmalfarbe/pandoc-latex-template/pull/78

...but noting in passing that the XeLaTeX-specific configuration mechanism used here (`\usepackage{ifxetex}`, `\ifxetex`, ..., `\fi`) may have an impact on the XeLaTeX-specific font selection options discussed in:

https://github.com/Wandmalfarbe/pandoc-latex-template/issues/68 (specifically https://github.com/Wandmalfarbe/pandoc-latex-template/issues/68#issuecomment-438408162).

**Comment by Wandmalfarbe** [comment]
The issue has already been discussed in https://github.com/silkeh/latex-sourcecodepro/pull/5 and fixed in https://github.com/silkeh/latex-sourcecodepro/commit/a62228bbe3d3fd02bc313d51061b892d2a4b0c82. Currently it is not released on CTAN that's why I merged your workaround. Thanks for the pull request!
